const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');
const source=fs.readFileSync(__dirname+'/../../app.js','utf8');const start=source.indexOf('async function loadProfile(){');const method=source.slice(start,source.indexOf('\n// ═',start));
function harness(response,onRpc,recovery={data:{restored:false}}){let reads=0;const c=vm.createContext({user:{id:'12345678-account',email:'fixture@example.invalid'},profile:null,Error,String,sb:{async rpc(name){if(name==='forma_restore_legacy')return recovery;assert.equal(name,'forma_access_status');if(onRpc)onRpc(c);return response;},from(name){reads++;assert.equal(name,'forma_profiles');return {select(){return this;},eq(){return this;},async maybeSingle(){return {data:{id:'12345678-account',full_name:'Fixture'}};}};}}});vm.runInContext(method,c);return {c,reads:()=>reads};}
test('pending account never reads financial profile and gets its own reference',async()=>{const h=harness({data:{status:'pending_validation',reference:'12345678-account'}});await assert.rejects(h.c.loadProfile(),e=>e.code==='FORMA_ACCESS_PENDING'&&e.message.includes('12345678'));assert.equal(h.reads(),0);});
test('status service failure blocks profile loading without fallback',async()=>{const h=harness({error:new Error('Unavailable')});await assert.rejects(h.c.loadProfile());assert.equal(h.reads(),0);});
test('missing or unknown status never permits entry',async()=>{const h=harness({data:{status:'unexpected'}});await assert.rejects(h.c.loadProfile());assert.equal(h.reads(),0);});
test('active account continues loading its own profile',async()=>{const h=harness({data:{status:'active'}});await h.c.loadProfile();assert.equal(h.reads(),1);assert.equal(h.c.profile.id,'12345678-account');});
test('account changed during access check cannot load the previous profile',async()=>{const h=harness({data:{status:'active'}},c=>{c.user={id:'another-account'};});await assert.rejects(h.c.loadProfile(),/Session changed/);assert.equal(h.reads(),0);});

test('failed recovery blocks entry and never exposes an empty replacement budget',async()=>{const h=harness({data:{status:'active'}},null,{error:new Error('recovery offline')});await assert.rejects(h.c.loadProfile(),e=>e.code==='FORMA_RECOVERY_FAILED');assert.equal(h.reads(),0);});
