const {test}=require('node:test');const a=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');
function harness({demo=false,admin=false,fail=false}={}){const els=new Map(),writes=[];let c;class El{constructor(id=''){this.id=id;this.value='';this.hidden=false;this.children=[];this.dataset={};this.isConnected=true;}set innerHTML(s){this.html=s;for(const m of s.matchAll(/id="([^"]+)"/g))if(!els.has(m[1]))els.set(m[1],new El(m[1]));}get innerHTML(){return this.html||''}prepend(x){this.children.unshift(x)}append(x){this.children.push(x)}insertBefore(x){this.children.push(x);els.set(x.id,x)}querySelectorAll(){return []}scrollIntoView(){}replaceChildren(x){this.children=[x]}}
const el=id=>{if(!els.has(id))els.set(id,new El(id));return els.get(id)};const query=table=>{let inserted;const chain={select(){return chain},eq(){return chain},order(){return chain},insert(x){inserted=x;writes.push({table,x});return chain},update(x){inserted=x;writes.push({table,x});return chain},single(){return Promise.resolve(fail?{error:{}}:{data:inserted})},maybeSingle(){return Promise.resolve({data:admin?{user_id:'A'}:null})},then(resolve,reject){return Promise.resolve(fail?{error:{}}:{data:table==='forma_courses'?[{id:'free',title:'Free',summary:'',language:'es',access_level:'free',icon:'📚'},{id:'paid',title:'Paid',summary:'',language:'es',access_level:'subscription',icon:'📚'}]:[]}).then(resolve,reject)}};return chain};
c=vm.createContext({window:{FORMA_DEMO:demo},document:{getElementById:el,createElement:()=>new El()},user:{id:'A'},sb:{from:query,rpc:async()=>({data:false}),auth:{onAuthStateChange(){}}},escapeHTML:x=>String(x).replaceAll('<','&lt;'),BANKS:{nubank:['Nubank']},bankMark:()=>'',fmt:x=>String(x),todayStr:()=> '2026-10-08',FormaIntent:require('../../finance-intent'),FormaCourseUtils:require('../../course-utils'),FormaLearning:require('../../learning-utils'),location:{origin:'https://forma-fin.vercel.app'},crypto:{randomUUID:()=> 'new-id'},toast(){},goPanel(){},renderBankPanel(){},setTimeout,clearTimeout,URL});vm.runInContext(fs.readFileSync(__dirname+'/../../education-accounts.js','utf8'),c);return{c,el,writes,section:c.document.getElementById('p-aprender').children[0]};}
const settle=()=>new Promise(r=>setImmediate(r));
test('demo accounts never write financial data',async()=>{const h=harness({demo:true});await h.el('manual-account-form').onsubmit({preventDefault(){}});a.equal(h.writes.length,0);h.c.goPanel('banco');await settle();a.match(h.el('manual-account-list').innerHTML,/Ejemplo/);});
test('non administrator cannot create courses',async()=>{const h=harness();await h.el('course-new').onclick();a.equal(h.el('course-editor').innerHTML,'');a.equal(h.writes.length,0);});
test('missing backend reports preparation without pretending a save',async()=>{const h=harness({fail:true});h.c.goPanel('banco');await settle();a.match(h.el('manual-account-list').innerHTML,/activar este módulo/);h.c.goPanel('aprender');await settle();a.match(h.section.innerHTML,/en preparación/);});
test('catalog offers free courses but does not open subscription lessons without entitlement',async()=>{const h=harness();h.c.goPanel('aprender');await settle();a.match(h.section.innerHTML,/data-course="free"/);a.doesNotMatch(h.section.innerHTML,/data-course="paid"/);a.match(h.section.innerHTML,/Requiere acceso de suscripción/);});
