const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');
const source=fs.readFileSync(__dirname+'/../../app.js','utf8');const start=source.indexOf('let passwordRecoveryActive=');const end=source.indexOf("document.getElementById('auth-retry')",start);
function setup(auth={}){const els={};const el=id=>els[id]||(els[id]={value:'',style:{},checkValidity:()=>true,focus(){}});const c=vm.createContext({document:{getElementById:el},hideEl:id=>el(id).style.display='none',showEl:id=>el(id).style.display='block',sb:{auth},switchTab(){},user:{id:'test'},profile:{},Error});vm.runInContext(source.slice(start,end),c);return {c,el};}
test('login network failure releases button and shows actionable error',async()=>{const h=setup({signInWithPassword:async()=>{throw Error('offline')}});h.el('l-email').value='fixture@example.invalid';h.el('l-pass').value='password';await h.c.doLogin();assert.equal(h.el('btn-login').disabled,false);assert.match(h.el('login-err').textContent,/Inténtalo/);});
test('signup uses independent callback, name only and requires eight characters',async()=>{let call;const h=setup({signUp:async args=>{call=args;return {data:{session:null}}}});h.el('s-name').value='Fixture';h.el('s-email').value='fixture@example.invalid';h.el('s-pass').value='1234567';await h.c.doSignup();assert.equal(call,undefined);h.el('s-pass').value='12345678';await h.c.doSignup();assert.equal(call.options.emailRedirectTo,'https://forma-fin.vercel.app/');assert.deepEqual(Object.keys(call.options.data),['full_name']);assert.equal(h.el('btn-signup').disabled,false);});
test('reset request does not assert that a particular account exists',async()=>{let call;const h=setup({resetPasswordForEmail:async (...args)=>{call=args;return {}}});h.el('r-email').value='fixture@example.invalid';await h.c.sendPasswordReset();assert.match(h.el('recovery-msg').textContent,/Si el correo está registrado/);assert.equal(call[1].redirectTo,'https://forma-fin.vercel.app/');});
test('reset backend failure is never displayed as sent',async()=>{const h=setup({resetPasswordForEmail:async()=>({error:Error('SMTP unavailable')})});h.el('r-email').value='fixture@example.invalid';await h.c.sendPasswordReset();assert.match(h.el('recovery-msg').className,/auth-err/);assert.equal(h.el('auth-send-reset').disabled,false);});
test('password changes require recovery state and matching passwords',async()=>{let writes=0;const h=setup({updateUser:async()=>{writes++;return {}},signOut:async()=>{}});h.el('r-pass').value='12345678';h.el('r-confirm').value='12345678';await h.c.saveRecoveredPassword();assert.equal(writes,0);h.c.showPasswordRecovery();h.el('r-confirm').value='different';await h.c.saveRecoveredPassword();assert.equal(writes,0);h.el('r-confirm').value='12345678';await h.c.saveRecoveredPassword();assert.equal(writes,1);assert.equal(h.el('r-pass').value,'');});
test('onboarding has no financial input or cloud write and opens no required editor',()=>{const section=source.slice(source.indexOf('const OB_STEPS='),source.indexOf('function obSkip'));assert.doesNotMatch(section,/ob-salary|ob-income-source|sb\.from|upsert|openOrcModal/);assert.match(section,/No necesitas saber cuánto ganas/);});
