const {test}=require('node:test');const a=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const F=require('../../finance-intent');
const app=fs.readFileSync(__dirname+'/../../app.js','utf8');const ctx=vm.createContext({});vm.runInContext(app.slice(app.indexOf('const CAT_GROUPS='),app.indexOf('function catInfo')),ctx);const categories=vm.runInContext("[...EXP_CATS.map(c=>({id:c.id,label:c.l,type:'expense'})),...INC_CATS.map(c=>({id:c.id,label:c.l,type:'income'}))]",ctx);const parse=s=>F.parse(s,{today:'2026-10-05',categories});
test('Spanish expense words and automatic category/date',()=>{const r=parse('Gasté veinticinco reales en Uber');a.equal(r.amount,25);a.equal(r.type,'expense');a.equal(r.category,'uber');a.equal(r.date,'2026-10-05');a.deepEqual(r.missing,[]);});
test('Portuguese numbers with cents and pharmacy',()=>{const r=parse('Gastei vinte e cinco reais e cinquenta centavos na farmácia');a.equal(r.amount,25.5);a.equal(r.category,'farmacia');a.equal(r.type,'expense');});
test('Uber Eats is food, Uber earnings are income',()=>{a.equal(parse('Gasté 40 en Uber Eats').category,'restaurantes');const r=parse('Gané 200 trabajando con Uber');a.equal(r.type,'income');a.equal(r.category,'freelance');});
test('Missing amounts and unknown categories never invent values',()=>{a.equal(parse('Gasté en Uber').amount,null);a.ok(parse('Gasté 25 en algo').missing.includes('category'));});
test('Multiple expenses and ambiguous numeric corrections require review',()=>{a.ok(parse('Gasté 25 en Uber y 50 en almuerzo').missing.includes('ambiguous_amount'));a.equal(parse('Gasté 25 no fueron 30 en Uber').amount,null);});
test('Negative values are not silently made positive; cents are cents',()=>{a.equal(parse('Gasté -25 en Uber').amount,null);a.equal(parse('Gasté menos veinte en Uber').amount,null);a.equal(parse('Gasté cincuenta centavos en Uber').amount,.5);});
test('Yesterday and valid explicit dates; invalid or ambiguous date stays pending',()=>{a.equal(parse('Ayer gasté 40 en almuerzo').date,'2026-10-04');a.equal(parse('Gasté 25 en Uber el 03/10/2026').date,'2026-10-03');a.ok(parse('Gasté 25 en Uber el 31/02/2026').missing.includes('date'));a.ok(parse('Gasté 25 en Uber el viernes').missing.includes('date'));});
test('Own-account transfers are not counted as income or expense',()=>{a.equal(parse('Pasé 500 a mi otra cuenta').transfer,true);});
test('Thousands and salary/prolabore classify into personal income',()=>{a.equal(parse('Recebi três mil de salário').amount,3000);a.equal(parse('Recibí 1.200,50 de pró-labore').category,'negocio');a.equal(parse('Recibí 1.200,50 de pró-labore').amount,1200.5);});
test('A preference affects only the supplied user context',()=>{const cs=[...categories,{id:'custom:mascota',label:'Mascota',type:'expense'}];a.equal(F.parse('Gasté 50 en comida para perro',{today:'2026-10-05',categories:cs,preferences:[{phrase:'comida para perro',category:'custom:mascota',type:'expense'}]}).category,'custom:mascota');a.notEqual(parse('Gasté 50 en comida para perro').category,'custom:mascota');});

test('meat purchases use the existing budget category in Spanish and Portuguese',()=>{for(const phrase of ['Gasté 50 reales en carne','Compra de carne 50 reales','Gastei cinquenta reais no açougue','Compré pescado por 50 reales']){const r=parse(phrase);a.equal(r.type,'expense',phrase);a.equal(r.category,'carne',phrase);a.equal(r.amount,50,phrase);a.deepEqual(r.missing,[],phrase);}});
test('meat at market and restaurant meals have distinct categories',()=>{a.equal(parse('Compré carne por 50 en el mercado').category,'carne');a.equal(parse('Gasté 50 en almuerzo con carne').category,'restaurantes');});
test('purchase without amount asks for it and never invents money',()=>{const r=parse('Compra de carne');a.equal(r.type,'expense');a.equal(r.category,'carne');a.equal(r.amount,null);a.ok(r.missing.includes('amount'));});

test('exact student phrase hice compras de carne 60 reales is saveable',()=>{const r=parse('hice compras de carne 60 reales');a.equal(r.type,'expense');a.equal(r.category,'carne');a.equal(r.amount,60);a.deepEqual(r.missing,[]);});
