const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
const source=fs.readFileSync('audit-improvements.js','utf8');
function harness({rpc={data:{id:'event-1'}},insert={data:null},direction='contribution',demo=false}={}){
 const els=new Map(),messages=[],calls=[],writes=[];let closed=0;
 const el=id=>{if(!els.has(id))els.set(id,{value:'',textContent:'',setAttribute(){},append(){},querySelector(){return{append(){}}},classList:{remove(){closed++}}});return els.get(id)};
 Object.assign(el('event-amount'),{value:'25'});el('event-date').value='2026-10-09';el('event-bank').value='nubank';el('event-location').value='Reserva';
 const row={id:'event-1',user_id:'student',goal_id:'goal',direction,amount:25,institution_code:'nubank',location_label:'Reserva',occurred_on:'2026-10-09'};
 const c=vm.createContext({$:el,document:{createElement:()=>el('status')},window:{FORMA_DEMO:demo},user:{id:'student'},remoteGoals:[{id:'goal',saved:0}],eventGoalId:'goal',eventDirection:direction,FormaIntent:require('../../finance-intent'),crypto:{randomUUID:()=> 'event-1'},toast:(m,ok)=>messages.push({m,ok}),demoNotice:()=>messages.push({m:'demo'}),openGoalEvent(){},saveGoalEvent(){},renderGoals:async()=>{},bounded:async p=>p,sb:{rpc:async(name,data)=>{calls.push({name,data});if(rpc instanceof Error)throw rpc;return rpc},from:table=>({insert:data=>{writes.push({table,data});return{select:()=>({single:async()=>insert.data?insert:{data:row}})}},select:()=>({eq(){return this},single:async()=>({data:row})})})}});
 vm.runInContext(source.slice(source.indexOf(' const eventStatus='),source.indexOf(' if(window.FORMA_DEMO)updateOverview();')),c);return{c,el,calls,writes,messages,get closed(){return closed}};
}
test('confirmed RPC saves once and closes only after server acknowledgement',async()=>{const h=harness();await h.c.saveGoalEvent();assert.equal(h.calls[0].name,'forma_save_goal_event');assert.equal(h.calls[0].data.p_id,'event-1');assert.equal(h.closed,1);assert.equal(h.writes.length,0)});
test('missing server function permits only an idempotent positive deposit',async()=>{const h=harness({rpc:{error:{code:'PGRST202'}}});await h.c.saveGoalEvent();assert.equal(h.writes.length,1);assert.equal(h.writes[0].data.id,'event-1');assert.equal(h.writes[0].data.source,'self_reported');assert.equal(h.closed,1)});
test('withdrawal cannot fall back to unprotected table INSERT',async()=>{const h=harness({rpc:{error:{code:'PGRST202'}},direction:'withdrawal'});await h.c.saveGoalEvent();assert.equal(h.writes.length,0);assert.equal(h.closed,0);assert.match(h.messages.at(-1).m,/protección de metas/)});
test('uncertain response preserves identity and refuses changed payload',async()=>{const h=harness({rpc:Error('timeout')});await h.c.saveGoalEvent();h.el('event-amount').value='30';await h.c.saveGoalEvent();assert.equal(h.calls.length,1);h.el('event-amount').value='25';await h.c.saveGoalEvent();assert.equal(h.calls.length,2);assert.equal(h.calls[0].data.p_id,h.calls[1].data.p_id);assert.equal(h.closed,0)});
test('wrong acknowledgement never reports a confirmed save',async()=>{const h=harness({rpc:{data:{id:'other-id'}}});await h.c.saveGoalEvent();assert.equal(h.closed,0);assert.match(h.messages.at(-1).m,/No se confirmó/)});
test('demonstration never writes a goal event',async()=>{const h=harness({demo:true});await h.c.saveGoalEvent();assert.equal(h.calls.length,0);assert.equal(h.writes.length,0)});
