const {test}=require('node:test');const a=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');
const src=fs.readFileSync(__dirname+'/../../voice-register.js','utf8');const method=src.slice(src.indexOf(' async function saveMovement('),src.indexOf('\n function saveDraft('));
const payload={date:'2026-10-05',amount:25,type:'expense',category:'uber',description:'Uber'};
function setup({demo=false,readFail=false,writeGate=null,edit=false,timeout=false,refreshFail=false}={}){const writes=[],elements={},statuses=[],toasts=[],record={id:'new-id',user_id:'A',...payload};let fail=readFail;const c=vm.createContext({Number,JSON,Error,FormaIntent:require('../../finance-intent'),crypto:{randomUUID:()=> 'new-id'},user:{id:'A'},generation:0,saving:false,pending:null,editVoice:edit?{id:'existing-id',uid:'A'}:null,draft:{},npRaw:'',month:'2026-10',demo:()=>demo,demoNotice:()=>statuses.push('demo'),categories:()=>[{id:'uber',type:'expense'}],clear:()=>statuses.push('clear'),$:id=>elements[id]??=(id==='amt-display'?{dataset:{},classList:{add(){}}}:{}),status:s=>statuses.push(s),toast:s=>toasts.push(s),voiceRequest:request=>timeout?Promise.race([Promise.resolve(request),new Promise((_,reject)=>setTimeout(()=>reject(new Error("timeout")),5))]):Promise.resolve(request),say(){},todayStr:()=> '2026-10-05',loadMonthData:async()=>{if(refreshFail)throw new Error("refresh failed")},card:{querySelector:()=>({})},sb:{rpc:async(name,args)=>{writes.push({name,args});if(writeGate)await writeGate;return{data:args.p_id};},from(){const chain={select(){return chain},eq(){return chain},update(data){writes.push({update:data});return chain},async single(){if(fail){fail=false;return{error:true};}return{data:edit?{...record,id:'existing-id'}:record};}};return chain;}}});vm.runInContext(method,c);return{c,writes,statuses,toasts};}
test('demo never sends financial writes',async()=>{const x=setup({demo:true});await x.c.saveMovement(payload);a.equal(x.writes.length,0);});
test('repeated save while pending sends one request',async()=>{let release;const gate=new Promise(r=>release=r),x=setup({writeGate:gate});const first=x.c.saveMovement(payload);await x.c.saveMovement(payload);a.equal(x.writes.length,1);release();a.equal(await first,true);});
test('read-back failure retains ID and retry uses same ID',async()=>{const x=setup({readFail:true});a.equal(await x.c.saveMovement(payload),false);a.equal(x.c.pending.id,'new-id');a.equal(await x.c.saveMovement(payload),true);a.deepEqual(x.writes.map(w=>w.args.p_id),['new-id','new-id']);});
test('changed payload cannot bypass an unconfirmed save',async()=>{const x=setup({readFail:true});await x.c.saveMovement(payload);await x.c.saveMovement({...payload,amount:30});a.equal(x.writes.length,1);});
test('account change before confirmation never announces success',async()=>{let release;const gate=new Promise(r=>release=r),x=setup({writeGate:gate});const pending=x.c.saveMovement(payload);x.c.user={id:'B'};release();a.equal(await pending,false);a.equal(x.toasts.length,0);});
test('voice correction updates existing row instead of creating movement',async()=>{const x=setup({edit:true});a.equal(await x.c.saveMovement(payload),true);a.ok(x.writes[0].update);a.equal(x.writes.filter(w=>w.name).length,0);});

test('invalid calendar date never reaches the save RPC',async()=>{const x=setup();a.equal(await x.c.saveMovement({...payload,date:'2026-02-31'}),false);a.equal(x.writes.length,0);});

test('a hung write stops loading, keeps the same ID and permits retry',async()=>{const x=setup({writeGate:new Promise(()=>{}),timeout:true});a.equal(await x.c.saveMovement(payload),false);a.equal(x.c.saving,false);a.equal(x.c.pending.id,'new-id');a.equal(x.c.$('voice-confirm').disabled,false);a.match(x.statuses.at(-1),/Vuelve a Guardar/);});
test('confirmed save remains successful when dashboard refresh fails',async()=>{const x=setup({refreshFail:true});a.equal(await x.c.saveMovement(payload),true);a.equal(x.c.pending,null);a.equal(x.c.saving,false);a.match(x.statuses.at(-1),/guardado y confirmado/);});
