const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const FormaIntent=require('../../finance-intent');
const s=fs.readFileSync(__dirname+'/../../voice-register.js','utf8');const section=s.slice(s.indexOf(' function promptFor('),s.indexOf(' function fillManual('));
function setup(){const els={},messages=[];const el=id=>els[id]??={value:'',addEventListener(name,fn){this[name]=fn;}};const c=vm.createContext({draft:{type:'expense',amount:25,category:'uber',date:'2026-10-07',description:'Uber',transfer:false,dateIssue:false},saving:false,pending:null,editVoice:null,categories:()=>[{id:'uber',type:'expense',label:'Uber'}],$:el,FormaIntent,todayStr:()=> '2026-10-07',escapeHTML:x=>String(x),fmt:x=>String(x),status:x=>messages.push(x),say(){},saveDraft(){},fillManual(){},manual:{},clear(){}});vm.runInContext(section,c);c.renderDraft();return{c,el,messages};}
test('preview provides date picker and yesterday keeps amount and category',()=>{const h=setup();assert.match(h.el('voice-preview').innerHTML,/id="voice-date" type="date"/);h.el('voice-date-yesterday').onclick();assert.equal(h.c.draft.date,'2026-10-06');assert.equal(h.c.draft.amount,25);assert.equal(h.c.draft.category,'uber');assert.equal(h.el('tx-date').value,'2026-10-06');});
test('manual date change updates voice draft instead of retaining the old date',()=>{const h=setup();h.el('tx-date').change({target:{value:'2026-09-30'}});assert.equal(h.c.draft.date,'2026-09-30');assert.equal(h.c.draft.dateIssue,false);});
test('impossible or empty dates block confirmation',()=>{const h=setup();h.c.changeDraftDate('2026-02-31');assert.equal(h.c.draft.dateIssue,true);assert.match(h.el('voice-preview').innerHTML,/id="voice-confirm" disabled/);h.c.changeDraftDate('');assert.equal(h.c.draft.dateIssue,true);h.el('voice-date-today').onclick();assert.equal(h.c.draft.dateIssue,false);});
test('voice-only correction fue ayer preserves the existing transaction details',()=>{const h=setup();h.c.interpret('fue ayer');assert.equal(h.c.draft.date,'2026-10-06');assert.equal(h.c.draft.amount,25);assert.equal(h.c.draft.category,'uber');});
test('relative date crosses month and year boundaries correctly',()=>{assert.equal(FormaIntent.parse('ayer',{today:'2026-10-01'}).date,'2026-09-30');assert.equal(FormaIntent.parse('ontem',{today:'2026-01-01'}).date,'2025-12-31');});
test('an unconfirmed save prevents date corrections and duplicate changed payload',()=>{const h=setup();h.c.pending={id:'pending'};h.c.changeDraftDate('2026-10-06');assert.equal(h.c.draft.date,'2026-10-07');assert.match(h.messages.at(-1),/pendiente/);});

test('missing amount is visible and can be completed without losing date or category',()=>{const h=setup();h.c.draft.amount=null;h.c.renderDraft();assert.match(h.el('voice-preview').innerHTML,/id="voice-amount"/);assert.match(h.el('voice-preview').innerHTML,/id="voice-confirm" disabled/);h.el('voice-amount').onchange({target:{value:'50'}});assert.equal(h.c.draft.amount,50);assert.equal(h.c.draft.category,'uber');assert.equal(h.c.draft.date,'2026-10-07');assert.doesNotMatch(h.el('voice-preview').innerHTML,/id="voice-confirm" disabled/);});

test('unknown type and category can be completed in the voice preview',()=>{const h=setup();h.c.draft.type=null;h.c.draft.category=null;h.c.renderDraft();assert.match(h.el('voice-preview').innerHTML,/id="voice-type"/);h.el('voice-type').onchange({target:{value:'expense'}});assert.match(h.el('voice-preview').innerHTML,/id="voice-category"/);h.el('voice-category').onchange({target:{value:'uber'}});assert.equal(h.c.draft.category,'uber');assert.doesNotMatch(h.el('voice-preview').innerHTML,/id="voice-confirm" disabled/);assert.equal(h.c.draft.amount,25);});
test('pending writes prevent changing missing type or category',()=>{const h=setup();h.c.draft.type=null;h.c.draft.category=null;h.c.renderDraft();h.c.pending={id:'pending'};h.el('voice-type').onchange({target:{value:'expense'}});h.el('voice-category').onchange({target:{value:'uber'}});assert.equal(h.c.draft.type,null);assert.equal(h.c.draft.category,null);});
