const {test}=require('node:test');const a=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');
const src=fs.readFileSync(__dirname+'/../../voice-register.js','utf8');
function setup(){const instances=[],els={},messages=[],phrases=[],timers=new Map();let n=0;class Recognition{constructor(){instances.push(this)}start(){}stop(){this.stopped=true}abort(){this.aborted=true}}
const c=vm.createContext({listening:false,saving:false,pending:null,cloud:false,generation:0,user:{id:'A'},recognition:null,recorder:null,recordTimer:null,window:{SpeechRecognition:Recognition},$:id=>els[id]??={value:'es-BR',setAttribute(k,v){this[k]=v}},status:x=>messages.push(x),interpret:x=>phrases.push(x),stopTracks(){},setTimeout:fn=>{timers.set(++n,fn);return n},clearTimeout:id=>timers.delete(id),demo:()=>false});vm.runInContext(src.slice(src.indexOf(' function resetCapture('),src.indexOf(' function clear('))+src.slice(src.indexOf(' async function capture('),src.indexOf("\n $('voice-start').onclick")),c);return{c,instances,els,messages,phrases,timers};}
test('recognized speech ends loading without waiting for an end event',async()=>{const h=setup();await h.c.capture();h.instances[0].onresult({results:[[{transcript:'Gasté 50 en carne'}]]});a.equal(h.c.listening,false);a.equal(h.els['voice-start']['aria-pressed'],'false');a.equal(h.timers.size,0);a.deepEqual(h.phrases,['Gasté 50 en carne']);});
test('silence and microphone errors stop loading with a recovery message',async()=>{const h=setup();await h.c.capture();h.instances[0].onend();a.equal(h.c.listening,false);a.match(h.messages.at(-1),/No recibimos/);await h.c.capture();h.instances[1].onerror({error:'not-allowed'});h.instances[1].onend();a.equal(h.c.listening,false);a.match(h.messages.at(-1),/permiso del micrófono/);});
test('watchdog aborts hung recognition and discards late results',async()=>{const h=setup();await h.c.capture();[...h.timers.values()][0]();a.equal(h.instances[0].aborted,true);a.equal(h.instances[0].onresult,null);a.equal(h.c.listening,false);a.match(h.messages.at(-1),/tardó demasiado/);a.equal(h.phrases.length,0);});
test('old recognition cannot reset a new capture',async()=>{const h=setup();await h.c.capture();h.instances[0].onend();await h.c.capture();h.instances[0].onend();a.equal(h.c.listening,true);});
test('request timeout rejects hung work and clears its timer',async()=>{let callback,cleared=false;const c=vm.createContext({Promise,Error,setTimeout:fn=>{callback=fn;return 1},clearTimeout:()=>cleared=true});vm.runInContext(src.slice(src.indexOf(' function voiceRequest('),src.indexOf(' function promptFor(')),c);const pending=c.voiceRequest(new Promise(()=>{}));callback();await a.rejects(pending,/timed out/);a.equal(cleared,true);});
