// FORMÁ: manual, personal finance companion. No bank balance or transfer is represented.
const BANKS={nubank:['Nubank','N','https://cdn.simpleicons.org/nubank/820AD1'],inter:['Inter','I','inter.svg'],mercadopago:['Mercado Pago','M','https://cdn.simpleicons.org/mercadopago/009EE3'],picpay:['PicPay','P','https://cdn.simpleicons.org/picpay/21C25E'],other:['Otro lugar','•','']};
let remoteGoals=[],goalEvents=[],learningDone=new Set(),eventGoalId=null,eventDirection='contribution';
const learning=[
 ['budget','1 · Tu primer presupuesto','Separa lo que esperas recibir de lo que ya recibiste. Revisa alquiler, transporte, comida y otras categorías de la planilla. Tu plan sirve para descubrir cuánto cuesta tu mes.','Abre Presupuesto en Resumen, completa el mes y después registra ingresos y gastos reales.'],
 ['reserve','2 · Reserva de emergencia','Una reserva ayuda con imprevistos. Calcula primero tus gastos esenciales mensuales; una meta inicial puede ser un mes y luego ampliarse según tu situación.','Crea una meta de tipo Reserva y anota únicamente el dinero que ya guardaste.'],
 ['goals','3 · Metas con lugar','Un viaje, una visita a la familia o una feria se vuelve más claro con monto y fecha. Puedes anotar en qué banco está cada parte, incluso si usas varios.','Crea un cofrinho y registra la ubicación de cada aporte real.'],
 ['selic','4 · Selic y rendimientos','La Selic es una tasa de referencia de Brasil. El rendimiento de una cuenta o producto puede diferir por reglas, impuestos, plazos y condiciones. Un cofrinho aquí no genera intereses ni consulta al banco.','Lee las condiciones del producto en tu banco antes de contar un rendimiento como ingreso recibido.'],
 ['investments','5 · Antes de invertir','Empieza por conocer tus gastos, organizar deudas y reserva. Aprende sobre liquidez, riesgo, costos e impuestos antes de elegir un producto. Este contenido es educativo.','Cuando tengas una base, continúa con los cursos de educación financiera de FORMÁ.']
];
function bankMark(code){const [name,initial,url]=BANKS[code]||BANKS.other;return `<span class="bank-chip">${url?`<img class="bank-logo" style="${code==='inter'?'width:48px':''}" src="${url}" alt="" data-forma-error="82"><span class="bank-fallback" style="display:none">${initial}</span>`:`<span class="bank-fallback">${initial}</span>`}${name}</span>`}
async function renderGoals(){
 if(!user)return;
 const el=document.getElementById('goals-list');if(!el)return;
 const [g,e]=await Promise.all([sb.from('forma_goals').select('id,name,target,saved,deadline,monthly_plan,goal_type').eq('user_id',user.id).order('created_at',{ascending:false}),sb.from('forma_goal_events').select('id,goal_id,direction,amount,institution_code,location_label,occurred_on').eq('user_id',user.id).order('occurred_on',{ascending:false})]);
 if(g.error||e.error){el.innerHTML='<p class="muted-note">No pudimos cargar tus metas. Intenta de nuevo.</p>';return}
 remoteGoals=g.data||[];goalEvents=e.data||[];
 paintGoals();
}
function paintGoals(){
 const el=document.getElementById('goals-list');
 updateGoalPreview();
 if(!remoteGoals.length){const old=loadGoals();el.innerHTML=`<div class="goal-item"><p>Comienza con una meta: reserva, viaje o visita familiar.</p><div class="goal-actions"><button data-forma-click="83">Crear mi primera meta</button>${old.length?'<button data-forma-click="84">Importar metas guardadas en este dispositivo</button>':''}</div></div>`;return}
 el.innerHTML=remoteGoals.map(goal=>{
  const ev=goalEvents.filter(x=>x.goal_id===goal.id);const balance=Number(goal.saved||0)+ev.reduce((s,x)=>s+(x.direction==='contribution'?1:-1)*Number(x.amount),0);const pct=Math.min(100,Math.max(0,Math.round(balance/Number(goal.target)*100)));
  const locations={};ev.forEach(x=>{const key=x.institution_code;locations[key]=(locations[key]||0)+(x.direction==='contribution'?1:-1)*Number(x.amount)});
  return `<div class="goal-item"><div class="goal-header"><span class="goal-name">${goal.goal_type==='reserve'?'🛡️':goalEmoji(goal.name)} ${escapeHTML(goal.name)}</span><strong>${pct}%</strong></div><div class="goal-track"><div class="goal-fill" style="width:${pct}%"></div></div><div class="goal-meta"><span>${fmt(balance)} declarados de ${fmt(goal.target)}</span><span>${goal.monthly_plan>0?fmt(goal.monthly_plan)+'/mes previsto':''}</span></div><p class="muted-note">${goal.deadline?'Fecha objetivo: '+escapeHTML(displayDate(goal.deadline))+' · ':''}Montos anotados por ti, sin verificación bancaria.</p><div>${Object.entries(locations).map(([k,v])=>`${bankMark(k)} <small>${fmt(v)}</small>`).join('')}</div><div class="goal-actions"><button data-forma-click="85" data-forma-arg0="${goal.id}">+ Anotar aporte</button><button data-forma-click="86" data-forma-arg0="${goal.id}">Anotar retiro</button></div><details><summary class="muted-note">Ver movimientos (${ev.length})</summary>${ev.length?ev.map(x=>`<div class="event-row"><span>${escapeHTML(displayDate(x.occurred_on))} · ${BANKS[x.institution_code]?.[0]||'Otro'} ${escapeHTML(x.location_label||'')}</span><strong>${x.direction==='contribution'?'+':'−'}${fmt(x.amount)}</strong></div>`).join(''):'<p class="muted-note">Aún no hay aportes anotados.</p>'}</details></div>`
 }).join('');
}
function openGoalModal(){['goal-name','goal-target','goal-monthly','goal-date'].forEach(id=>document.getElementById(id).value='');document.getElementById('goal-overlay').classList.add('open')}
async function saveGoal(){const name=document.getElementById('goal-name').value.trim(),target=Number(document.getElementById('goal-target').value),monthly=Number(document.getElementById('goal-monthly').value||0),deadline=document.getElementById('goal-date').value||null;if(!name||name.length>100||!Number.isFinite(target)||target<=0||target>999999999||!Number.isFinite(monthly)||monthly<0){toast('Revisa la meta y los montos',false);return}const {error}=await sb.from('forma_goals').insert({user_id:user.id,name,target,monthly_plan:monthly,deadline,saved:0,goal_type:/reserva|emergencia/i.test(name)?'reserve':'custom'});if(error){toast('No se pudo crear la meta',false);return}closeGoalModal();toast('Meta creada');renderGoals()}
function openGoalEvent(id,direction){eventGoalId=id;eventDirection=direction;document.getElementById('event-title').textContent=direction==='contribution'?'Anotar dinero guardado':'Anotar dinero retirado';document.getElementById('event-amount').value='';document.getElementById('event-location').value='';document.getElementById('event-date').value=todayStr();document.getElementById('event-overlay').classList.add('open')}
async function saveGoalEvent(){const amount=Number(document.getElementById('event-amount').value),institution_code=document.getElementById('event-bank').value,location_label=document.getElementById('event-location').value.trim(),occurred_on=document.getElementById('event-date').value;const goal=remoteGoals.find(g=>g.id===eventGoalId);if(!goal||!Number.isFinite(amount)||amount<=0||amount>999999999||!occurred_on){toast('Revisa el monto y la fecha',false);return}const balance=Number(goal.saved||0)+goalEvents.filter(e=>e.goal_id===goal.id).reduce((s,e)=>s+(e.direction==='contribution'?1:-1)*Number(e.amount),0);if(eventDirection==='withdrawal'&&amount>balance+0.001){toast('El retiro supera lo anotado en esta meta',false);return}const {error}=await sb.from('forma_goal_events').insert({user_id:user.id,goal_id:goal.id,direction:eventDirection,amount,institution_code,location_label,occurred_on,source:'self_reported'});if(error){toast('No se pudo guardar el movimiento',false);return}document.getElementById('event-overlay').classList.remove('open');toast('Anotación guardada');renderGoals()}
async function importOldGoals(){const old=loadGoals();if(!old.length)return;const rows=old.filter(g=>g.name&&Number(g.target)>0).map(g=>({user_id:user.id,name:String(g.name).slice(0,100),target:Number(g.target),saved:Math.max(0,Number(g.saved)||0),deadline:g.date||null,monthly_plan:0,goal_type:'custom'}));if(!rows.length)return;const {error}=await sb.from('forma_goals').insert(rows);if(error){toast('No se pudieron importar las metas',false);return}localStorage.setItem('forma_goals_imported_'+user.id,'1');toast('Metas importadas; revisa los saldos declarados');renderGoals()}
async function loadLearning(){if(!user)return;const {data,error}=await sb.from('forma_learning_progress').select('lesson_key').eq('user_id',user.id);if(error){toast('No pudimos cargar el progreso',false);return}learningDone=new Set((data||[]).map(x=>x.lesson_key));renderLearning()}
function renderLearning(){document.getElementById('learning-list').innerHTML=learning.map(([key,title,body,action])=>`<details class="lesson-card"><summary>📖 ${title}</summary><p>${body}</p><p><strong>Para practicar:</strong> ${action}</p>${key==='selic'?'<p><a href="https://www.bcb.gov.br/controleinflacao/taxaselic" target="_blank" rel="noopener">Consulta el Banco Central de Brasil</a></p>':''}</details>`).join('')}
async function markLesson(){toast('El avance se valida en los videocursos. Las guías son material de consulta.',false)}
const oldGoPanel=goPanel;goPanel=function(id){oldGoPanel(id);if(id==='metas')renderGoals();if(id==='aprender')loadLearning()};
const oldOpenOrc=openOrcModal;openOrcModal=function(){oldOpenOrc();const root=document.getElementById('orc-cats');root.innerHTML=`<div class="orc-totals" id="orc-live"></div><details class="orc-group" open><summary>💰 Entradas previstas</summary>${INC_CATS.map(c=>`<div class="orc-row"><span class="orc-label">${c.i} ${escapeHTML(c.l)}</span><input class="orc-input" type="number" id="oc-inc-${c.id}" placeholder="0" value="${budgets['income:'+c.id]||''}" min="0" step="0.01" inputmode="decimal"></div>`).join('')}</details>`+CAT_GROUPS.filter(g=>g.id!=='trabajo').map((g,i)=>`<details class="orc-group" ${i===0?'open':''}><summary>${g.i} ${g.l}</summary>${g.subs.map(c=>`<div class="orc-row"><span class="orc-label">${c.i} ${escapeHTML(c.l)}</span><input class="orc-input" type="number" id="oc-${c.id}" placeholder="0" value="${budgets[c.id]||''}" min="0" step="0.01" inputmode="decimal"></div>`).join('')}</details>`).join('');root.insertAdjacentHTML('beforeend',CAT_GROUPS.filter(g=>g.id==='trabajo').flatMap(g=>g.subs).map(c=>`<input type="hidden" id="oc-${c.id}" value="${budgets[c.id]||0}">`).join(''));root.oninput=refreshOrc;refreshOrc()};
function refreshOrc(){const sum=ids=>ids.reduce((s,id)=>s+(Number(document.getElementById(id)?.value)||0),0),inc=sum(INC_CATS.map(c=>'oc-inc-'+c.id)),exp=sum(EXP_CATS.map(c=>'oc-'+c.id));document.getElementById('orc-live').innerHTML=`Entradas previstas: <strong>${fmt(inc)}</strong><br>Gastos previstos: <strong>${fmt(exp)}</strong><br>Diferencia del plan: <strong>${fmt(inc-exp)}</strong>`}
