// The public example uses memory only and never reads or writes financial records.
let demoMode=false;
const overviewColors=['#6950C8','#47A68D','#E7B05E','#77A1D5','#D78197','#8D94A8'];
const navPaths={resumo:'M3 10l9-7 9 7v10H3z M9 20v-7h6v7',registrar:'M12 4v16 M4 12h16',historico:'M5 3h14v18H5z M8 8h8 M8 12h8 M8 16h5',metas:'M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18 M12 7a5 5 0 1 0 0 10 5 5 0 0 0 0-10 M12 11v2',aprender:'M3 4h7l2 2 2-2h7v15h-7l-2 2-2-2H3z M12 6v15',anual:'M4 5h16v16H4z M8 2v6 M16 2v6 M4 10h16',alunos:'M9 4a3 3 0 1 0 0 6 3 3 0 0 0 0-6 M3 21v-4a6 6 0 0 1 12 0v4 M17 4a3 3 0 0 1 0 6 M18 14a5 5 0 0 1 3 7'};
for(const [id,d] of Object.entries(navPaths)){const el=document.querySelector('#nb-'+id+' .ni');if(el)el.innerHTML=`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${d}"/></svg>`}
document.querySelector('#nb-resumo .nl').textContent='Inicio';
const basicResume=renderResume;renderResume=function(){basicResume();updateOverview()};
function updateOverview(){
 const expense=txs.filter(t=>t.type==='expense').reduce((s,t)=>s+Number(t.amount),0),planned=EXP_CATS.reduce((s,c)=>s+Number(budgets[c.id]||0),0),plannedIncome=INC_CATS.reduce((s,c)=>s+Number(budgets['income:'+c.id]||0),0);
 const percent=planned>0?Math.round(expense/planned*100):0,color=!planned?'#A2ABC0':percent>100?'#C54F61':percent>80?'#D1A246':'#13866B';
 document.getElementById('thermo-ring').style.background=`conic-gradient(${color} ${Math.min(100,percent)*3.6}deg,#EDF0F5 0deg)`;
 document.getElementById('thermo-percent').textContent=planned>0?percent+'%':'—';
 const status=document.getElementById('thermo-status');status.textContent=!planned?'Sin presupuesto':percent>100?'Sobre el plan':percent>80?'Atención':'Dentro del plan';status.style.color=color;status.style.background=!planned?'#EDF0F5':percent>100?'#FBECEE':percent>80?'#FFF3DD':'#E6F5EF';
 document.getElementById('thermo-title').textContent=!planned?'Primero, tu presupuesto':percent>100?'Revisa tus prioridades':percent>80?'Acompaña lo que falta':'Vas dentro de tu plan';
 document.getElementById('thermo-copy').textContent=!planned?'Planifica tus gastos para entender cuánto cuesta tu mes.':percent>100?'Registraste '+fmt(expense-planned)+' por encima de lo previsto.':'Quedan '+fmt(planned-expense)+' en tu plan de gastos.';
 const hasPlan=planned>0&&plannedIncome>0,hasRecords=txs.length>0;
 document.getElementById('guide-step').textContent=hasPlan?(hasRecords?'PASO 3 DE 4':'PASO 2 DE 4'):'PASO 1 DE 4';
 document.getElementById('guide-title').textContent=!hasPlan?'Descubre cuánto cuesta tu mes':!hasRecords?'Ahora, acompaña tu día a día':'Dale un propósito a tu ahorro';
 document.getElementById('guide-copy').textContent=!hasPlan?'Arma tu presupuesto con las categorías que ya conoces.':!hasRecords?'Anota lo que realmente recibiste y lo que realmente gastaste.':'Crea una reserva o una meta para visitar a tu familia.';
 const action=document.getElementById('guide-action');action.textContent=!hasPlan?'Armar presupuesto':!hasRecords?'Registrar movimiento':'Crear una meta';action.onclick=!hasPlan?openOrcModal:!hasRecords?()=>goPanel('registrar'):openGoalModal;
 document.getElementById('journey-budget').classList.toggle('done',hasPlan);document.getElementById('journey-record').classList.toggle('done',hasRecords);document.getElementById('journey-goal').classList.toggle('done',remoteGoals.length>0);
 const groups={};txs.filter(t=>t.type==='expense').forEach(t=>{const g=CAT_GROUPS.find(g=>g.subs.some(c=>c.id===t.category));const name=g?g.l:'Otros';groups[name]=(groups[name]||0)+Number(t.amount)});
 const rows=Object.entries(groups).sort((a,b)=>b[1]-a[1]);let angle=0;const segments=rows.map(([name,amount],i)=>{const start=angle;angle+=expense?amount/expense*360:0;return `${overviewColors[i%overviewColors.length]} ${start}deg ${angle}deg`});
 document.getElementById('category-donut').style.background=rows.length?`conic-gradient(${segments.join(',')})`:'#EDF0F5';document.getElementById('category-count').textContent=rows.length;
 document.getElementById('category-legend').innerHTML=rows.length?rows.map(([name,amount],i)=>`<div class="legend-row"><div class="legend-heading"><span class="legend-name"><i class="legend-dot" style="background:${overviewColors[i%overviewColors.length]}"></i>${escapeHTML(name)}</span><strong>${fmt(amount)}</strong><small>${Math.round(amount/expense*100)}%</small></div><div class="category-bar"><span style="width:${Math.min(100,amount/expense*100)}%;background:${overviewColors[i%overviewColors.length]}"></span></div></div>`).join(''):'<p class="muted-note">El gráfico aparecerá al registrar tus primeros gastos.</p>';
 updateGoalPreview();
}
function updateGoalPreview(){const el=document.getElementById('goals-preview');if(!el)return;if(!remoteGoals.length){el.innerHTML='<p class="muted-note">Reserva, viaje, familia. Dale un lugar a tu próxima meta.</p><button class="action-main" data-forma-click="88">Crear mi primera meta</button>';return}el.innerHTML=remoteGoals.slice(0,2).map(g=>{const events=goalEvents.filter(e=>e.goal_id===g.id),saved=Number(g.saved||0)+events.reduce((s,e)=>s+(e.direction==='contribution'?1:-1)*Number(e.amount),0),pct=Math.max(0,Math.min(100,Math.round(saved/Number(g.target)*100))),banks=[...new Set(events.map(e=>e.institution_code))];return `<div class="mini-goal"><div class="mini-goal-head"><span>${escapeHTML(g.name)}</span><span>${pct}%</span></div><div class="goal-track"><div class="goal-fill" style="width:${pct}%"></div></div><small>${fmt(saved)} anotados de ${fmt(g.target)}</small>${banks.map(bankMark).join('')}</div>`}).join('')}
function demoNotice(){toast('Vista de ejemplo. Entra a tu cuenta para guardar tus datos.',false)}
function startDemo(){
 demoMode=true;window.FORMA_DEMO=true;month=todayMonth();
 const date=month+'-01';txs=[{id:'demo-income',type:'income',category:'salario',amount:3200,date,description:'Ingreso mensual'},{id:'demo-rent',type:'expense',category:'alquiler',amount:1000,date,description:'Alquiler del mes'},{id:'demo-food',type:'expense',category:'supermercado',amount:450,date,description:'Compras del mes'},{id:'demo-bus',type:'expense',category:'uber',amount:180,date,description:'Transporte'},{id:'demo-light',type:'expense',category:'luz',amount:120,date,description:'Cuenta de luz'},{id:'demo-course',type:'expense',category:'universidad',amount:100,date,description:'Curso de idioma'}];
 budgets={'income:salario':3200,alquiler:1000,supermercado:600,uber:220,luz:150,universidad:180,restaurantes:150};
 remoteGoals=[{id:'demo-reserve',name:'Reserva de emergencia',target:6000,saved:0,monthly_plan:300,deadline:null,goal_type:'reserve'},{id:'demo-family',name:'Visitar a mi familia',target:2400,saved:0,monthly_plan:200,deadline:null,goal_type:'custom'}];
 goalEvents=[{id:'demo-event-1',goal_id:'demo-reserve',direction:'contribution',amount:1500,institution_code:'nubank',location_label:'Caixinha de reserva',occurred_on:date},{id:'demo-event-2',goal_id:'demo-family',direction:'contribution',amount:800,institution_code:'inter',location_label:'Viaje familiar',occurred_on:date}];
 learningDone=new Set(['budget']);hideEl('loading-screen');hideEl('auth-screen');showEl('app-screen');document.getElementById('demo-banner').hidden=false;document.getElementById('tb-greeting').textContent='Hola, Ana';document.getElementById('tb-role').textContent='FORMÁ Financiero · Ejemplo';document.getElementById('tb-avatar').textContent='A';document.getElementById('month-label').textContent=monthLabel(month);document.getElementById('tx-date').value=todayStr();renderQuickCats();renderAllCats();goPanel('resumo');paintGoals();renderTxList();renderEvoChart();
}
const realMonthLoad=loadMonthData;loadMonthData=async function(){if(demoMode){document.getElementById('month-label').textContent=monthLabel(month);renderResume();renderTxList();return}return realMonthLoad()};
const realGoalsRender=renderGoals;renderGoals=async function(){if(demoMode){paintGoals();return}return realGoalsRender()};
const realLearningLoad=loadLearning;loadLearning=async function(){if(demoMode){renderLearning();return}return realLearningLoad()};
const realLogout=doLogout;doLogout=async function(){if(demoMode){location.href=location.pathname;return}remoteGoals=[];goalEvents=[];learningDone=new Set();txs=[];budgets={};return realLogout()};
const realEvo=renderEvoChart;renderEvoChart=async function(){if(!demoMode)return realEvo();const canvas=document.getElementById('evo-chart'),ctx=canvas.getContext('2d'),w=canvas.width=canvas.clientWidth*2,h=canvas.height=320;ctx.clearRect(0,0,w,h);ctx.font='22px sans-serif';ctx.fillStyle='#7C879B';const values=[[2700,1800],[3000,2300],[2900,2100],[3200,2400],[3100,2200],[3200,1850]];values.forEach(([income,expense],i)=>{const x=30+i*(w-55)/6,bw=Math.max(8,(w-55)/20);ctx.fillStyle='#47A68D';ctx.fillRect(x,h-45-income/15,bw,income/15);ctx.fillStyle='#D78197';ctx.fillRect(x+bw+5,h-45-expense/15,bw,expense/15);ctx.fillStyle='#7C879B';let d=new Date(Number(month.slice(0,4)),Number(month.slice(5))-6+i,1);ctx.fillText(d.toLocaleDateString('es',{month:'short'}),x,h-15)});};
const realAnnual=loadAnnualData;loadAnnualData=async function(){if(!demoMode)return realAnnual();document.getElementById('annual-year-label').textContent=annualYear;document.getElementById('annual-list').innerHTML='<p class="muted-note">Vista de ejemplo: el presupuesto anual de tu cuenta aparecerá aquí con los movimientos que registres.</p>'};
// All write handlers are guarded before their original authenticated implementation.
for(const name of ['saveTx','saveOrc','saveGoal','saveGoalEvent','markLesson','importOldGoals','saveTxEdit','deleteTxConfirm']){const fn=window[name];window[name]=async function(...args){if(demoMode){demoNotice();return}return fn(...args)}}
const registerPanel=document.getElementById('p-registrar');
registerPanel.insertAdjacentHTML('afterbegin','<div class="register-heading"><span class="eyebrow">MI DÍA A DÍA</span><h2>Registrar movimiento</h2><p>Solo lo que realmente recibiste o gastaste.</p></div>');
document.getElementById('quick-cats').insertAdjacentHTML('beforebegin','<div class="daily-category"><label for="daily-category-select">Categoría</label><select id="daily-category-select" class="inp-simple" data-forma-change="89"></select></div>');
function renderDailyCategory(){const el=document.getElementById('daily-category-select');el.innerHTML=txType==='income'?INC_CATS.map(c=>`<option value="${c.id}">${escapeHTML(c.l)}</option>`).join(''):CAT_GROUPS.filter(g=>g.id!=='trabajo').map(g=>`<optgroup label="${escapeHTML(g.l)}">${g.subs.map(c=>`<option value="${c.id}">${escapeHTML(c.l)}</option>`).join('')}</optgroup>`).join('');el.value=selCat}
const baseSetType=setTxType;setTxType=function(type){baseSetType(type);renderDailyCategory()};
const baseQuickRender=renderQuickCats;renderQuickCats=function(){baseQuickRender();renderDailyCategory()};
if(new URLSearchParams(location.search).get('vista')==='ejemplo')startDemo();
