-- Managed recovery only: reconcile independent writes before returning students to the original.
begin;
drop policy if exists forma_independent_cutover_closed on public.forma_profiles;
drop policy if exists forma_independent_cutover_closed on public.forma_budgets;
drop policy if exists forma_independent_cutover_closed on public.forma_transactions;
drop policy if exists forma_independent_cutover_closed on public.forma_goals;
drop policy if exists forma_independent_cutover_closed on public.forma_goal_events;
drop policy if exists forma_independent_cutover_closed on public.forma_learning_progress;
drop policy if exists forma_independent_cutover_closed on public.forma_usage_daily;
drop policy if exists forma_independent_cutover_closed on public.forma_admin_members;
drop policy if exists forma_independent_cutover_closed on public.forma_support_settings;
drop policy if exists forma_cutover_insert on public.forma_budgets;
drop policy if exists forma_cutover_update on public.forma_budgets;
drop policy if exists forma_cutover_delete on public.forma_budgets;
drop policy if exists forma_cutover_insert on public.forma_transactions;
drop policy if exists forma_cutover_update on public.forma_transactions;
drop policy if exists forma_cutover_delete on public.forma_transactions;
drop policy if exists forma_cutover_insert on public.forma_goals;
drop policy if exists forma_cutover_update on public.forma_goals;
drop policy if exists forma_cutover_delete on public.forma_goals;
drop policy if exists forma_cutover_insert on public.forma_goal_events;
drop policy if exists forma_cutover_update on public.forma_goal_events;
drop policy if exists forma_cutover_delete on public.forma_goal_events;
drop policy if exists forma_cutover_insert on public.forma_learning_progress;
drop policy if exists forma_cutover_update on public.forma_learning_progress;
drop policy if exists forma_cutover_delete on public.forma_learning_progress;
grant execute on function public.forma_access_status() to authenticated;
grant execute on function public.forma_admin_access_review() to authenticated;
grant execute on function public.forma_admin_report(integer) to authenticated;
grant execute on function public.forma_admin_validate_access(uuid) to authenticated;
grant execute on function public.forma_record_access(text) to authenticated;
grant execute on function public.forma_save_movement(uuid,date,numeric,text,text,text) to authenticated;
grant execute on function public.forma_voice_claim(integer) to authenticated;
commit;
